# Individual Project 2 
## McKenzee Masters
## DS160-01
## Version 1

### Part A

In [4]:
import numpy as np
array=np.arange(10,50,10)
array

array([10, 20, 30, 40])

In [5]:
array.resize(2,2)
array

array([[10, 20],
       [30, 40]])

In [9]:
sq=(array**2)
print(sq)

[[ 100  400]
 [ 900 1600]]


In [10]:
hd=(sq+100)
print(hd)

[[ 200  500]
 [1000 1700]]


In [11]:
five=(hd*5)
print(five)

[[1000 2500]
 [5000 8500]]


In [13]:
sqrt=(np.round(np.sqrt(five)))
print(sqrt)

[[32. 50.]
 [71. 92.]]


### Part B

In [49]:
array1=np.arange(3,28,3)
array1.resize(3,3)
print(array1)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [48]:
array2=np.linspace(10,20,9)
array2.resize(3,3)
print(array2)

[[10.   11.25 12.5 ]
 [13.75 15.   16.25]
 [17.5  18.75 20.  ]]


In [50]:
array3=array1*array2
print(array3)

[[ 30.   67.5 112.5]
 [165.  225.  292.5]
 [367.5 450.  540. ]]


### Part C

In [52]:
a=np.load("process1.npy")
b=np.load("process2.npy")
c=np.load("process3.npy")
d=np.load("process4.npy")
e=np.load("process5.npy")

In [54]:
array11=np.vstack([a,b,c,d,e])
print(array11)

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]


In [55]:
print("Mean of Columns", np.round(array11.mean(axis=0)) )

Mean of Columns [72. 28. 46. 12. 48.]
